# Base configs
baseurl: "https://robertoreale.me/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics:

# UI configs
title: "Photography by Roberto Reale"
subtitle: "See the world through my eyes!"
author: "Roberto Reale"
email: "rober.reale@gmail.com"
bio: "My research in photography centers around portraits, street photography, and sometimes architecture."
license: "All the pictures are licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/rober.reale"
  twitter: "https://www.twitter.com/roberto_reale"
  instagram: "https://www.instagram.com/rober.reale"
  dribbble: "https://dribbble.com/robertoreale"
  linkedin: "https://in.linkedin.com/in/robertoreale"
  github: "https://www.github.com/robertoreale"
