# Base configs
baseurl: "https://robertoreale.me/leakedshots"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics:

# UI configs
title: "Leaked Shots"
subtitle: "My photography project."
author: "Roberto Reale"
email: "rober.reale+leakedshots@gmail.com"
bio: "My name is Roberto Reale, and my projects center around portraits, street photography, and architecture."
license: "All the pictures are licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/leakedshots"
  flickr: "https://www.flickr.com/photos/roberto_reale/albums/72157686093529441"
  instagram: "https://www.instagram.com/leakedshots"
  twitter: "https://www.twitter.com/leakedshots"
  github: "https://www.github.com/robertoreale/leakedshots"
