# Base configs
baseurl: "https://robertoreale.me/leakedshots"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics:

# UI configs
title: "Leaked Shots"
subtitle: "An ongoing project in street photography"
author: "Roberto Reale"
email: "rober.reale+leakedshots@gmail.com"

bio: "Leaked Shots is a tentative exploration of the liquid boundary between public and private. When referring to a leaked shot we usually mean a paparazzo-stolen, tipically nude portrait of a random celebrity on the lookout for an even greater, albeit cheesy, popularity. As far as my project is concerned, however, the moments and faces and gestures I strive to capture are not meant to be sheltered from the gaze of the passer-by; on the contrary, they are inherently public, just subtly playing with the very concept of privacy.

As Bauman writes in his book Collateral damage, «the area of privacy is turning into a site of incarceration, the owner of private space being condemned and doomed to stew in his or her own juices». Hence, our inner self tries harder and harder to ooze out of the waning restraint we struggle to exercise; indeed, as in the old tale of Gyges of Lidia, we need to summon others to witness our secrets, «to make them everybody’s shared property», lest our valuable self should pass unheeded.

Which is why, when in public space, we are at the same time willing to reveal and striving to conceal ourselves."

license: "All the pictures are licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/leakedshots"
  flickr: "https://www.flickr.com/photos/roberto_reale/albums/72157686093529441"
  instagram: "https://www.instagram.com/leakedshots"
  twitter: "https://www.twitter.com/leakedshots"
  github: "https://www.github.com/leakedshots"
